telegram:
  bot:
    token: 1515

server:
  port: 8080

spring:
  application:
    name: telegrambot
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/advent
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10               # Оптимально для средних нагрузок
      connection-timeout: 30000           # 30 секунд
      idle-timeout: 600000                # 10 минут
      max-lifetime: 1800000               # 30 минут
      pool-name: SpringBootHikariCP
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    #show-sql: true                       # Только для разработки
    #open-in-view: false

logging:
  level:
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: adventbot.log
    path: ./logs